### ISSUE TITLE
Page Model couldn't return something else as a field object?

### ISSUE THREAD

**Issue by creichel** [getkirby-v2/kirby#178]
I wanted to make a gallery for each page which should return false if there's no page called `galerie`. But I'm always getting a field object even if I'm really sure that I would return a boolean value.

This is my function for my Page Model:

```
public function galleryImages() {

  $output = false;

  $galleryPage = $this->children()->visible()->find('galerie');
  if(!is_bool($galleryPage) && $galleryPage->hasImages()) $output = $galleryPage->images()->sortBy('sort', 'asc');
  return $output;
}
```

My code is already really messy because I've tried to do everything to get a boolean when I have to. 
But it turns out that even this function ...

```
public function galleryImages() {
  return false;
}
```

... doesn't returns false but a field object. 

What's the solution? Is it a bug or a dev problem?

**Comment by bastianallgeier** [comment]
I need more context here. How do use it in your template? I'm not in the office this week. So please excuse if I'm not able to reply instantly

**Comment by servicethinker** [comment]
Allright. 

The context is simple: I have a template which has to display a gallery if there's one (with images inside).
So I have such structure:

    Page
    |- Gallery
       |- Image1.jpg
       |- Image2.jpg
     etc...
 
 The Page has to display the images from the Gallery page which is simply just a page used as an archive.

The little for-loop to display the images is following:

    $output = false;

    if($page->galleryImages()->isEmpty()) {
      $gallery = $page->galleryImages();
      $output  .= '<section class="info gallery">'
                . '<h2 class="icon-image">Bildergalerie</h2>'
                . '<p>';
      foreach($gallery as $image)
      {
        $imageThumb = thumb($image, array('width' => 50, 'height' => 50, 'upscale' => true, 'crop' => true));($image);
        $imageGallery = thumb($image, array('height' => 1000), false);
        $output  .= '<a rel="gallery" href="'.$imageGallery.'" alt="" title="'.$image->caption().'">'
                  . $imageThumb
                  . '</a>';
      }
      $output  .= '</p></section>';
    }

And in the end I'm `echo`'ing the output where I want to have it. 

## Solution 1: *failed*
The idea was to use the `galleryImage()` function like any other function: simply check if it's empty and when it's not: build the gallery block. 

The thing is that it doesn't work. Dumping `$page->galleryImages()->isEmpty()` brings up this value:
`              `
Yes, it's really empty. But not as I thought it would be. It's *always* empty. 

## Solution 2: *failed*
Allright, trying out some other solution:
Instead of asking `if($page->galleryImages()->isEmpty())` I've tried to ask `if($page->galleryImages() == false)` or `if($page->galleryImages() == "")` or `if($gallery = $page->galleryImages())` or even `if(empty($page->galleryImages()))` - the result is always false or always true which means that I'm getting always an error when I don't have any gallery on my page but trying to make a thumb from nothing (because the if-clause is always true) or I'm getting nothing at all (because it's always false).


## Solution 3: *failed and frustrated*

*sigh* Okay, rebuilding the whole structure to something bit more messy one:

    Page
    |- Image1.jpg
    |- Image2.jpg
     etc...

My custom function `galleryImages()` got shrink'd to something teeny tiny:

    public function galleryImages() {

      if ($this->showgallery() == false) return false;
      return $this->images()->sortBy('sort', 'asc');
    }

*(Psst: I've recognized in this part the whole power of Page Models: refactoring was amazingly fast!)*
But all what I've tried ended to the same big question mark of the other solutions. 

I hope I've made it clear where I'm stuck. Everything what I've tried out doesn't work. Now I'm [frustrated](http://youtu.be/qE0L-wjUm50) :-(

**Comment by lukasbestle** [comment]
There's no reason to [pay double](http://youtu.be/9p_FzRW_Vv4), no, to be frustrated, we can get this to work. :)

---

I have one possible problem in mind: Have you verified that the page model gets loaded and is being applied to that page? Non-defined fields always return an empty field value, but if it is defined, it should return whatever you return from the method.

There are some simple ways you can debug this:

- Include a line somewhere in the "global" scope of the page model file that echoes some text to verify the file gets loaded.
- Do the same within the `galleryImages` method to verify the method gets called.

**Comment by servicethinker** [comment]
Done. The page Model and the method are getting called. That's what I've also tested before. but when I want to call `$page->galleryImages()->isEmpty()`(or similar ones)  I'm getting neither a value nor a boolean.
 
When I'm trying to dump all those things with `var_dump($page->galleryImages()->isEmpty())` the page aborts completely at the point where I want to `var_dump()` it.

Hard to crack, huh?

**Comment by lukasbestle** [comment]
What does `var_dump(get_class($page));` say?

**Comment by servicethinker** [comment]
First of all, thank you @lukasbestle for your great support. I know that I'm not the best coder so the case that I have a not-working code is greater than in case of Kirby.

## Solution 4: YES!
The first error I've found today in an other project was the fact that I've simply seen the screencast and thought **when there's no exclusive Page Model for the current Template Kirby takes automatically the `DefaultPage` model if it's exists** (I've seen the video again and thought: "Yeah, the same thing like in templates happens to models" - like Bastian said).

*BEEEP!* My computer said no. And of course: this was the wrong way. So I've duplicated my default.php Page Model and edited it for every damn template I have (srsly @bastianallgeier you should load automatically DefaultPage if it exists... or bring up something like a "base" template or Page Model).

Before I've found this solution, `var_dump(get_class($page->galleryImages()));` said `string(5) "Field"` which was legit and this thing I've spotted in the very first comment. So even if the field doesn't exists - Kirby tries to make a field object which shouldn't happen here. 
Now it says `string(5) "Files" which is something I've expected. And when there's no image it returns a boolean. 

**Solved**


Now my advices for @bastianallgeier:

- It would be awesome if Page Models could inherit from a Default Page Model or something else which should be something you need for every single page.

### ... and:
DON'T say that the same thing like in templates happens to models. I've misunderstood this as "Oh cool. When there's no Page Model found, it takes default.php. Easy!".

**Comment by lukasbestle** [comment]
Great that you got it to work. :)

What you propose can actually already be done in a DRY way: Simply let your template page models extend the `DefaultPage` class (I haven't tested this, so you might have to `require_once` the default page model from your other page models). This will make the methods from the default page model available in all others. What that doesn't solve though is that you would have to create empty page models for every template, even if you wouldn't otherwise have needed one.

You are right that this can be considered a bug (at least in my opinion). If @bastianallgeier agrees, I can create a PR that fixes this.

**Comment by servicethinker** [comment]
It's better to drink a dry wine than having an empty glass. ;-)

Your `DRY`-solution works like a charm :-) Thank you!

**Comment by lukasbestle** [comment]
You are welcome. :)

**Comment by andi1984** [comment]
+1 for @servicethinker's advice
